version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:18.2-alpine
    container_name: blitzscale-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blitzscale_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blitzscale-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d blitzscale_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Redis
  redis:
    image: redis:8.6-alpine
    container_name: blitzscale-redis
    ports:
      - "6379:6379"
    networks:
      - blitzscale-network

  # Apache Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: blitzscale-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - blitzscale-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: blitzscale-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/blitzscale_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - blitzscale-network

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: blitzscale-zipkin
    ports:
      - "9411:9411"
    networks:
      - blitzscale-network

volumes:
  postgres_data:

networks:
  blitzscale-network:
    driver: bridge